### ISSUE TITLE
Add links to internal resources

### ISSUE THREAD

**Issue by mukrop** [zverinec/zverinec-web#5]
Add link to (so that new members can easily find the resources):
- Redmine for issue tracker
- gDrive

**Comment by repli2dev** [comment]
Good point.
What you mean by gDrive? Whole folder or just some parts of it such as collection of humour?

**Comment by mukrop** [comment]
Whole folder. The public parts are linked elsewhere. Possibly both whole folder and public subfolder. The point being easy navigation for members (Heno was looking for something recently and couldn't find the gDrive folder, similar case with Moutes and Redmine).

**Comment by repli2dev** [comment]
Done.
