### ISSUE TITLE
Nasty mixing of tabs and spaces

### ISSUE THREAD

**Issue by malinajan** [zverinec/zverinec-web#9]
Our web is a giant nasty mixture of tabs and spaces. We shall use only only one of these! And here starts the flame: which one?

**Comment by JanPokorny** [comment]
https://www.youtube.com/watch?v=CxK_nA2iVXw

...a vážně: navrhuji nasadit https://www.npmjs.com/package/js-beautify , navzdory názvu umí i CSS a HTML a jde z něj udělat pre-commit hook.

**Comment by yaqwsx** [comment]
Just do it! Make your dreams come true!

https://www.youtube.com/watch?v=VAVLOHbqWd4&ab_channel=AutomaticTriple


Dne 29. 10. 18 v 23:48 Jan Pokorný napsal(a):

**Comment by mukrop** [comment]
The one doing it has the privilege to choose according to their liking :-}.
(Although I slightly prefer spaces.)

**Comment by malinajan** [comment]
Done.
